on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@3eee20cf311ef238a2220fb57f5b70ce72efa4dd
        with:
          token: ${{ secrets.RELEASE_PR_TOKEN }}
          release-type: node
          fork: true
          package-name: release-please-action
