on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@2.4.0
        with:
          token: ${{ secrets.RELEASE_PR_TOKEN }}
          release-type: node
          fork: true
          package-name: release-please-action
          command: release-pr
  release-please-release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@2.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action
          command: github-release
