on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v1.2.1
        with:
          token: ${{ secrets.RELEASE_CLA_SIGNED }}
          release-type: node
          package-name: release-please-action
