on:
  push:
    branches:
      - master
name: coverage
jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/release-please-action@9291b92aca4939d0cc2781f26504c638ce1ba534
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action
