on:
  push:
    branches:
      - master
name: coverage
jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/release-please-action@e72afe059a2eae50d319b3a4cee2a31479886fe8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action
